### ISSUE TITLE
Define Rebase Logic for conflicts

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/document-drive#44]
_Before we can start this issue we ideally have a clear idea of the users signature's location/function/relation to the operations._

**Summary:**
We identified a critical need to add a basic conflict resolution mechanism.
This mechanism is aimed at enhancing the timing aspects and potentially utilizing GraphQL subscriptions for pushing changes. The primary focus is to implement an auto-rebase mechanic that triggers a rebase upon receiving conflicting operations between clients.

**Details:**
Objective: Implement a conflict resolution mechanism to handle conflicts between operations from different clients effectively.

**Scope:**
Improve timing aspects related to operation conflicts.
Investigate the feasibility of using GraphQL subscriptions for real-time updates.

**Develop an auto-rebase mechanic that:**
Triggers upon detecting a new operation conflicting with the current operation.
Carefully considers the execution context and how clients get updated with changes.
Utilizes the skip mechanism to undo a batch of operations if necessary.

**Challenges:**
Ensuring that the rebase mechanism does not cause loops where the server sends rebase operations to clients, leading to potential new conflicts.
Resolving conflicts effectively when different clients apply divergent operations, ensuring that the application of a skip operation leads to a consensus state without creating further conflicts.

**Technical Analysis Required:**
A examination of how the skip mechanism currently handles operation indexes and values, and whether it can distinguish between different operations at the same index with a skip value. Determination of conditions that create conflicts and how they can be resolved without introducing inconsistencies.

**Conflict Resolution Fallbacks:**
Development of a strategy for handling unresolved conflicts, possibly marking files as conflicted and figuring out a robust method to deal with exceptions.
Consideration of implementing conflict status at the document level rather than the drive level to prevent entire projects from being blocked due to conflicts in individual documents.

**Action Items:**

- [ ] Technical Exploration: Conduct a technical analysis to understand the current handling of operation conflicts and the feasibility of integrating GraphQL subscriptions.
- [ ] Mechanism Design: Design and document the proposed auto-rebase mechanism, including handling of edge cases and potential conflicts.
- [ ] Documentation & Testing: Ensure comprehensive documentation of the conflict resolution process and implement thorough testing scenarios to validate the mechanism under various conflict conditions.

**Comment by CallmeT-ty** [comment]
@acaldas @gpuente 
I've used the transcript + GPT(as experiment) and what i was able to captured yesterday to generate a first a first ticket for the Rebase Logic initiative that we talked about yesterday during core dev meeting. Does it make sense to you? Is anything missing or is there anything you'd like to add to get started with this (when priority is right).

**Comment by gpuente** [comment]
conflict resolution exploration doc:
https://docs.google.com/document/d/17aeOSP1jhGcG8QDy7Lmg3jQe6ZaCov3hEYELKybhDl0/edit?usp=sharing
